### ISSUE TITLE
The clock widget is showing the incorrect time when set to the 24-hour clock format.

### ISSUE THREAD

**Issue by enescala** [avinayak/minim#47]
The clock widget, when set to the 24-hour clock format, isn't displaying the correct time. Instead of displaying 12:00 at noon, it's showing 00:00.
Google Chrome, latest.

**Comment by salomaoparkour** [comment]
I can confirm this
![image](https://github.com/avinayak/minim/assets/890826/903ad759-880c-427f-8491-af68ee3d7b77)

**Comment by avinayak** [comment]
fixed this!

**Comment by salomaoparkour** [comment]
![image](https://github.com/avinayak/minim/assets/890826/25c23a53-f633-427c-bf26-e34d477087e1)
Not solved yet =(
